#!/bin/sh
#modified lukes smiths torrent module for dwmblocks this one just show an arrow icon if transmission daemon is active
# and if you click on it it opens transmission-gtk

: <<'END_COMMENT'
transmission-remote -l | grep % |
	sed " # The letters are for sorting and will not appear.
	s/.*Stopped.*/A 🛑/;
	s/.*Seeding.*/Z 🌱/;
	s/.*100%.*/N ✅/;
	s/.*Idle.*/B 🕰️/;
	s/.*Uploading.*/L ⬆️/;
	s/.*%.*/M ⬇️/" |
		sort -h | uniq -c | awk '{print $3 $1}' | paste -sd ' ' -

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e stig ;;
	2) td-toggle ;;
	3) notify-send "🌱 Torrent module" "\- Left click to open stig.
- Middle click to toggle transmission.
- Shift click to edit script.
Module shows number of torrents:
🛑: paused
🕰: idle (seeds needed)
🔼: uploading (unfinished)
🔽: downloading
✅: done
🌱: done and seeding" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

END_COMMENT

# Check if Transmission daemon is active
transmission_active=$(ps aux | grep '[t]ransmission-daemon' | awk '{print $11}')

# Display triangle icon if Transmission daemon is active, otherwise nothing
if [ -n "$transmission_active" ]; then
    transmission_status=" "
else
    transmission_status=""
fi

# Display the triangle icon for Transmission daemon status
echo "$transmission_status"

case $BLOCK_BUTTON in
	1) transmission-gtk ;;  #1) setsid -f "$TERMINAL" -e stig ;;
	2) td-toggle ;;
	3) notify-send "🌱 Torrent module" "\- Left click to open stig.
- Middle click to toggle transmission.
- Shift click to edit script.
Module shows if torrent is on";;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
