#!/bin/sh
# stolen from the status bar sb-select but this one is for the binding on keyboard
kb="$(setxkbmap -query | grep -oP 'layout:\s*\K\w+')" || exit 1

kb_choice="$(awk '/! layout/{flag=1; next} /! variant/{flag=0} flag {if ($1 == "us" || $1 == "ru" || $1 == "gr") print $2, "- " $1}' /usr/share/X11/xkb/rules/base.lst | dmenu -l 15)"

[ -z "$kb_choice" ] && exit 0

kb="$(echo "$kb_choice" | awk '{print $3}')"

setxkbmap "$kb"

pkill -RTMIN+30 "${STATUSBAR:-dwmblocks}";
